### PR TITLE
Master mind

### PR DESCRIPTION
**Pull request by AndrewSimons3**
## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] All tests passed: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript: 30 points

**Checkpoint 2**
- [ ] The application works as it should: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript and the DOM API: 30 points

**Checkpoint 3**
- [ ] Use of React: 25 points
- [ ] Accesses an API: 25 points
- [ ] Proper use of documentation (commenting on code): 25 points
- [ ] The application functions as it should: 25 points

### CODE REVIEW

**Review by anthonyjsilva — CHANGES_REQUESTED** [review]
@AndrewSimons3 
This is not running for me at all.

```
  #mastermind()
Guess again!
    1) should register a guess and generate hints
You guessed it!
    2) should be able to detect a win

  #generateHint()
    3) should generate hints
    4) should generate hints if solution has duplicates


  0 passing (9ms)
  4 failing

  1) #mastermind()
       should register a guess and generate hints:

      AssertionError [ERR_ASSERTION]: 0 == 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (04week/mastermind.js:111:14)
      at processImmediate (internal/timers.js:439:21)

  2) #mastermind()
       should be able to detect a win:
     AssertionError [ERR_ASSERTION]: true == 'You guessed it!'
      at Context.<anonymous> (04week/mastermind.js:114:14)
      at processImmediate (internal/timers.js:439:21)

  3) #generateHint()
       should generate hints:

      AssertionError [ERR_ASSERTION]: 'undefined-undefined' == '2-2'
      + expected - actual

      -undefined-undefined
      +2-2
      
      at Context.<anonymous> (04week/mastermind.js:120:14)
      at processImmediate (internal/timers.js:439:21)

  4) #generateHint()
       should generate hints if solution has duplicates:

      AssertionError [ERR_ASSERTION]: 'undefined-undefined' == '1-1'
      + expected - actual

      -undefined-undefined
      +1-1
      
      at Context.<anonymous> (04week/mastermind.js:123:14)
      at processImmediate (internal/timers.js:439:21)



```

**Comment by AndrewSimons3** [comment]
tests were failing because I implemented the colors library

it was comparing 2-2 to a colors formatted version of the 'hint'

**Comment by AndrewSimons3** [comment]
@anthonyjsilva tests are working now

**Review by anthonyjsilva — APPROVED** [review]
@AndrewSimons3 
Good to merge!

**Pull request merged**
